### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 1522402210** [cr4shcod3/pureblood#1]
mac

PureBlood(WebPentest)> 02
Traceback (most recent call last):
  File "pureblood.py", line 936, in <module>
    main()
  File "pureblood.py", line 906, in main
    web_pentest()
  File "pureblood.py", line 590, in web_pentest
    web_pentest()
  File "pureblood.py", line 859, in web_pentest
    set_url(target, 1)
  File "pureblood.py", line 447, in set_url
    web_pentest()
  File "pureblood.py", line 609, in web_pentest
    print ('{0}='.format(red) * int(sizex))
NameError: global name 'sizex' is not defined

**Comment by cr4shcod3** [comment]
I will update the script for that error. I will add get width for MAC

**Comment by cr4shcod3** [comment]
Error fix in PureBlood v2

**Comment by 1522402210** [comment]
python pureblood.py
Traceback (most recent call last):
  File "pureblood.py", line 97, in <module>
    elif platform.system() == 'Linux' or platform.sysmtem() == 'Darwin':
AttributeError: 'module' object has no attribute 'sysmtem'

**Comment by cr4shcod3** [comment]
Done. Fixed
