### ISSUE TITLE
Issue on Windows 7 Python 2.7

### ISSUE THREAD

**Issue by pedrodj** [cr4shcod3/pureblood#11]
PureBlood(WebPentest)> 10

Traceback (most recent call last):
  File "pureblood.py", line 2639, in <module>
    main()
  File "pureblood.py", line 2619, in main
    web_pentest()
  File "pureblood.py", line 2575, in web_pentest
    set_target(target, 1)
  File "pureblood.py", line 1675, in set_target
    web_pentest()
  File "pureblood.py", line 2284, in web_pentest
    wp_cms_detect = cweb_pentest.cms_detect(hostname)
  File "pureblood.py", line 1428, in cms_detect
    for i in cd_soup_div.find_all('span', attrs={'class': 'nowrap'}):
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by kingxiaofire** [comment]
try sudo  pip3 install -r requirements.txt
