### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by pedrodj** [cr4shcod3/pureblood#3]
Traceback (most recent call last):
  File "pureblood.py", line 936, in <module>
    banner()
  File "pureblood.py", line 430, in banner
    print (banner)
  File "C:\Python36\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python36\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python36\lib\site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Python36\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3-8: character maps to <undefined>

Installed all req.

any fix?

**Comment by cr4shcod3** [comment]
You installed the colorama right? Try pip install colorama if its not yet installed.

**Comment by theInfectedDrake** [comment]
It is a UnicodeError, so you need to handle the whole format as Unicode, such as `utf-8` encoding. Seems to be a big bug. And btw, @cr4shcod3 , this is not at all an error due to `colorama`.

**Comment by cr4shcod3** [comment]
@pedrodj Also can you tell me what CLI you are using?

**Comment by theInfectedDrake** [comment]
@cr4shcod3 change the full work environment sntirely to Unicode and that should solve it and btw, you should really stop using `colorama`. These use age old libraries with big syntaxes. Instead use `hue` (https://github.com/s0md3v/hue).

**Comment by cr4shcod3** [comment]
Thanks for the suggestion. I will try it. I will use it on pureblood v2

**Comment by cr4shcod3** [comment]
Fixed
