### ISSUE TITLE
Python 2.7 Windows 7

### ISSUE THREAD

**Issue by pedrodj** [cr4shcod3/pureblood#5]
$ python2 pureblood.py

Traceback (most recent call last):
  File "pureblood.py", line 2571, in <module>
    banner()
  File "pureblood.py", line 1574, in banner
    print (banner)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-7: ordinal not in range(128)

Any fix?

**Comment by cr4shcod3** [comment]
Fixed.
